### PR TITLE
Draft of the resource template for snowflake ml

### PR DESCRIPTION
**Pull request by skirmer**
Still developing but edits and notes welcome!

### CODE REVIEW

**Comment by skirmer** [comment]
Not sure I understand the current linting failure- @jsignell advice?

**Comment by skirmer** [comment]
Once we resolve the linting matter, I think this is ready for review!

**Review by jnolis — APPROVED** [review]
I approved this but I have a few minor changes.

Also, I wasn't sure where to put this comment, but I would move `saturncloud-logo.png` to the S3 public bucket so then we don't have to worry about it if we move the notebook (or like if we were to have it copied to the docs)

**Comment by skirmer** [comment]
Ok, got all the notes incorporated!

**Comment by jsignell** [comment]
@forana just pointed out that this PR introduced a 98MB file to this repository. We need to find a different place to put that file. Probably s3.

**Pull request merged**
