### PR TITLE
Label already set by prefect-saturn

### PR DESCRIPTION
**Pull request by bhperry**
Requested in: https://github.com/saturncloud/saturn/pull/1398#pullrequestreview-522922760

prefect-saturn will handle setting the default Saturn labels for flows now: https://github.com/saturncloud/prefect-saturn/pull/20

### CODE REVIEW

**Review by jameslamb — CHANGES_REQUESTED** [review]
I love this!

But I think we need to either:

* hold off on merging this PR until the release with the Prefect label changes has gone out
* update the Prefect Cloud tutorial

That tutorial was written when the example repos were still in flux, so it tells people to get this notebook by `wget`-ing it from GitHub: https://www.saturncloud.io/docs/tutorials/prefect-cloud/#create-and-register-a-flow.

If we merge this right now, that tutorial will be broken. Specifically, people who run this code with the current or next release of Saturn (which don't have the label changes), will have their flows run with only the label `["webhook-storage"]`, which, though unlikely, might mean that their flow runs on a non-Saturn Prefect Cloud agent in their Prefect Cloud tenantt.

I'm still a bit leery about telling people, in https://github.com/saturncloud/docs/blob/main/content/en/docs/Tutorials/prefect-cloud.md, to use the `examples-cpu` project since there isn't currently a way to easily recreate that project from the UI if you deleted it.

So my preference is to cut this PR against the release branch for whatever release will have the agent label changes, then to NOT merge the "release back into main" PR in this repo until that release has gone out to all customers.

**Comment by bhperry** [comment]
> I love this!
> 
> But I think we need to either:
> 
> * hold off on merging this PR until the release with the Prefect label changes has gone out
> * update the Prefect Cloud tutorial
> 
> That tutorial was written when the example repos were still in flux, so it tells people to get this notebook by `wget`-ing it from GitHub: https://www.saturncloud.io/docs/tutorials/prefect-cloud/#create-and-register-a-flow.
> 
> If we merge this right now, that tutorial will be broken. Specifically, people who run this code with the current or next release of Saturn (which don't have the label changes), will have their flows run with only the label `["webhook-storage"]`, which, though unlikely, might mean that their flow runs on a non-Saturn Prefect Cloud agent in their Prefect Cloud tenantt.
> 
> I'm still a bit leery about telling people, in https://github.com/saturncloud/docs/blob/main/content/en/docs/Tutorials/prefect-cloud.md, to use the `examples-cpu` project since there isn't currently a way to easily recreate that project from the UI if you deleted it.
> 
> So my preference is to cut this PR against the release branch for whatever release will have the agent label changes, then to NOT merge the "release back into main" PR in this repo until that release has gone out to all customers.

Right, will probably need to hold off on merging this until the feature is released, like with the docs PR. I'd be a little hesitant to merge to a release branch, because it would be very easy for someone to mistakenly merge that back to main without thinking about it if other work gets added.

**Comment by jameslamb** [comment]
@bhperry let me know when it's time for this, I can come back and approve

**Comment by bhperry** [comment]
@jameslamb 2 months later..... this is nearly ready to merge :laughing: 

The newer saturn images are out on community. As soon as 2021.01.13 goes out to enterprise they will all have the updated images as well for examples.

**Review by jameslamb — APPROVED** [review]
woo! :rocket:

**Pull request merged**
