### PR TITLE
Don't use ref for old-photos repo

### PR DESCRIPTION
**Pull request by jsignell**
I was too aggressive in adding references to every repo listed in every saturn.json.  I think this is the only external repo that doesn't point to saturncloud/examples

Integration test run: https://github.com/saturncloud/release-images/runs/4941609587?check_suite_focus=true

### CODE REVIEW

**Review by bhperry — APPROVED** [review]
LGTM

**Comment by jsignell** [comment]
@nathanballou this needs more than this change unfortunately. Is the image right for this? It is using a CPU image.

**Comment by nathanballou** [comment]
Yup. I needed to use PyTorch on CPU due to weird CUDA errors with the library I was using.

**Comment by jsignell** [comment]
Ok I'm putting it on daily to see what's going on.

**Comment by jsignell** [comment]
WHOA I just tried this out and it is super cool! I think the issue is that if you don't upload any photos the notebook fails. Probably it could do something more graceful, but for now we just won't run it on unit tests.

FYI I did get some warnings:

```python-traceback
Running Stage 1: Overall restoration
/srv/conda/envs/saturn/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
initializing the dataloader
model weights loaded
directory of testing image: /home/jovyan/examples/examples/old-photos/Upload-Photos-Here
processing photo.jpg
/srv/conda/envs/saturn/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Mapping: You are using multi-scale patch attention, conv combine + mask input
Now you are processing photo.png
/srv/conda/envs/saturn/lib/python3.9/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
Finish Stage 1 ...


Running Stage 2: Face Detection
/srv/conda/envs/saturn/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
1
Finish Stage 2 ...


Running Stage 3: Face Enhancement
/srv/conda/envs/saturn/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
dataset [FaceTestDataset] of size 1 was created
The size of the latent vector size is [16,16]
Network [SPADEGenerator] was created. Total number of parameters: 92.1 million. To see the architecture, do print(network).
hi :)
Finish Stage 3 ...


Running Stage 4: Blending
/srv/conda/envs/saturn/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Finish Stage 4 ...


All the processing is done. Please check the results.
```
but the thing finished.

**Pull request merged**
