### PR TITLE
Update images to 2020.09.25

### PR DESCRIPTION
**Pull request by jsignell**

### CODE REVIEW

**Review by jameslamb — COMMENTED** [review]
has @rikturr tested the examples with these new images?

**Comment by jsignell** [comment]
Probably not, and should def wait for https://github.com/saturncloud/images/pull/95 to be in and built before testing

**Comment by jameslamb** [comment]
oh ok, got it. Then I don't think I can give it a :heavy_check_mark: yet

**Comment by jsignell** [comment]
We need to merge this to fulfill our existing promise that we will use the most recent images with the examples. I am going to make sure the notebooks run through on 9-25 then I think we should merge.

**Comment by jsignell** [comment]
Ok so do I need to get snowflake creds and set up prefect, or is it enough that the cred-less examples pass? So far I have tested:

### examples-cpu
 - [x] nyc-taxi   ~~-> all passed, but having trouble getting the dashboard deployed.... getting path not found :roll_eyes:~~
 - [ ] nyc-taxi-snowflake
 - [ ] prefect  
 - [ ] snowflake

### examples-gpu
 - [x] nyc-taxi
 - [ ] nyc-taxi-snowflake

**Comment by jameslamb** [comment]
> Ok so do I need to get snowflake creds and set up prefect, or is it enough that the cred-less examples pass? So far I have tested:
> 
> ### examples-cpu
> * [ ]  nyc-taxi
> * [ ]  nyc-taxi-snowflake
> * [ ]  prefect
> * [ ]  snowflake
> 
> ### examples-gpu
> * [x]  nyc-taxi
> * [ ]  nyc-taxi-snowflake

I can get you credentials for all of them. You can just re-use my existing test accounts for Prefect Cloud and Snowflake.

By the way, only one of the examples in `examples-cpu/prefect` requires Prefect Cloud...the other one is intended to be run as a Saturn deployment.

**Comment by jsignell** [comment]
I haven't tested them all yet, but seeing as they don't work on 2020.08.28 (dask-saturn 0.0.4 is incompatible with Atlas 2020.09.25). I think we should go ahead and merge this. @jameslamb

**Review by jameslamb — APPROVED** [review]
sure fine with me

**Pull request merged**
