### PR TITLE
moving files around

### PR DESCRIPTION
**Pull request by jameslamb**
ok one more "breaking changes out of #2" PR. This pull request proposes moving the files in this repo around to match the directory structure proposed in #3 .

Look at the before and after below (generated with `tree -a examples/`). The propose here is that, as of the `after`, this repo would correspond to ~two~ new projects in the Saturn UI:

* `cpu`
* `gpu`

~I think this is a better level of difference than having `example-cpu` (for example), because it allows us to avoid the restriction that all CPU projects have to use the same image and start script.~

**before**

```text
examples/
├── example-cpu
│   ├── dask-examples
│   ├── nyc-taxi-dashboard
│   │   └── dashboard.ipynb
│   └── nyc-taxi-ml
│       ├── hyperparameter-dask.ipynb
│       ├── hyperparameter-scikit.ipynb
│       ├── random-forest-scikit.ipynb
│       ├── xgboost-dask.ipynb
│       └── xgboost.ipynb
├── example-gpu
│   └── nyc-taxi-ml
│       ├── random-forest-rapids.ipynb
│       └── xgboost-rapids.ipynb
└── taxi-cpu
    └── machine-learning
```

**after**

```text
examples/
├── cpu
│   ├── nyc-taxi
│   │   ├── dashboard
│   │   │   └── dashboard.ipynb
│   │   ├── machine-learning
│   │   │   ├── hyperparameter-dask.ipynb
│   │   │   ├── hyperparameter-scikit.ipynb
│   │   │   ├── .ipynb_checkpoints
│   │   │   │   └── xgboost-dask-checkpoint.ipynb
│   │   │   ├── random-forest-scikit.ipynb
│   │   │   ├── xgboost-dask.ipynb
│   │   │   └── xgboost.ipynb
│   │   └── README.md
│   ├── prefect
│   │   ├── flow.png
│   │   ├── prefect-scheduled-scoring.ipynb
│   │   └── README.md
│   ├── README.md
│   └── .saturn
│       ├── saturn.json
│       └── start
└── gpu
    ├── nyc-taxi
    │   ├── machine-learning
    │   │   ├── random-forest-rapids.ipynb
    │   │   └── xgboost-rapids.ipynb
    │   └── README.md
    ├── README.md
    └── .saturn
        ├── saturn.json
        └── start
```

<details><summary>after (original proposal)</summary>

```text
examples/
├── prefect
│   ├── flow.png
│   ├── prefect-scheduled-scoring.ipynb
│   └── README.md
├── taxi-cpu
│   ├── dashboard
│   │   └── dashboard.ipynb
│   └── machine-learning
│       ├── hyperparameter-dask.ipynb
│       ├── hyperparameter-scikit.ipynb
│       ├── random-forest-scikit.ipynb
│       ├── xgboost-dask.ipynb
│       └── xgboost.ipynb
└── taxi-gpu
    └── machine-learning
        ├── random-forest-rapids.ipynb
        └── xgboost-rapids.ipynb
```
</details>

### CODE REVIEW

**Comment by jameslamb** [comment]
ok @rikturr @jsignell could you please take another look? I think I've changed this to be consistent with what we agreed on in the team meeting today.

You can run `tree -a examples/` from the root of the repo.

**Comment by jsignell** [comment]
This looks right to me, only comment is I think the notebooks should be flat. So:
```
examples/
├── cpu
│   ├── nyc-taxi
│   │   ├── dashboard.ipynb
│   │   ├── hyperparameter-dask.ipynb
│   │   ├── hyperparameter-scikit.ipynb
│   │   ├── random-forest-scikit.ipynb
│   │   ├── xgboost-dask.ipynb
│   │   └── xgboost.ipynb
│   │   └── README.md
```

**Comment by jameslamb** [comment]
> This looks right to me, only comment is I think the notebooks should be flat. So:
> 
> ```
> examples/
> ├── cpu
> │   ├── nyc-taxi
> │   │   ├── dashboard.ipynb
> │   │   ├── hyperparameter-dask.ipynb
> │   │   ├── hyperparameter-scikit.ipynb
> │   │   ├── random-forest-scikit.ipynb
> │   │   ├── xgboost-dask.ipynb
> │   │   └── xgboost.ipynb
> │   │   └── README.md
> ```

ok I'll change it

**Comment by rikturr** [comment]
will the name of the project be based on the folder name? because I think `examples-cpu` looks better for a user than just `cpu`

**Comment by jameslamb** [comment]
> will the name of the project be based on the folder name? because I think `examples-cpu` looks better for a user than just `cpu`

ok I'll change it back and we can agree the name of the project will be based on the name of the folder

**Comment by jameslamb** [comment]
ok I think I've addressed https://github.com/saturncloud/examples/pull/6#issuecomment-676592266 and https://github.com/saturncloud/examples/pull/6#issuecomment-676593598

**Review by jsignell — APPROVED** [review]
This is great! Good to have such clear expectations from the start

**Pull request merged**
